<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Squirrel.Caching\Squirrel.Caching.csproj" />
    <ProjectReference Include="..\..\..\src\Squirrel.Core\Squirrel.Core.csproj" />
    <ProjectReference Include="..\..\..\src\Squirrel.Integration.Wolverine\Squirrel.Integration.Wolverine.csproj" />
    <ProjectReference Include="..\..\..\src\Squirrel.SerilogLogging\Squirrel.SerilogLogging.csproj" />
    <ProjectReference Include="..\..\..\src\Squirrel.Persistence.EfCore.Postgres\Squirrel.Persistence.EfCore.Postgres.csproj" />
    <ProjectReference Include="..\..\..\src\Squirrel.Persistence.Mongo\Squirrel.Persistence.Mongo.csproj" />
    <ProjectReference Include="..\..\..\src\Squirrel.Security\Squirrel.Security.csproj" />
    <ProjectReference Include="..\..\..\src\Squirrel.Web\Squirrel.Web.csproj" />
  </ItemGroup>

  <!-- What xunit NuGet Packages Should I Use? - https://xunit.net/docs/nuget-packages-->
  <ItemGroup Label="XUnit">
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Testcontainers.Redis" />
    <PackageReference Include="xunit.v3.extensibility.core" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Extensions.Logging.InMemory" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Testcontainers.MongoDb" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.RabbitMq" />
    <PackageReference Include="WebMotions.Fake.Authentication.JwtBearer" />
    <PackageReference Include="WireMock.Net" />
    <PackageReference Include="Respawn" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="FluentAssertions.Web" />
    <PackageReference Include="NSubstitute.Analyzers.CSharp" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="AutoBogus" />
    <PackageReference Include="AutoBogus.NSubstitute" />
    <PackageReference Include="Hypothesist" />
  </ItemGroup>

</Project>
