<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Squirrel.Core\Squirrel.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="Microsoft.Extensions.Resilience" />
    <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" />
  </ItemGroup>

</Project>
