<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Squirrel.Core\Squirrel.Core.csproj" />
    <ProjectReference Include="..\Squirrel.Validation\Squirrel.Validation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
    <PackageReference Include="WolverineFx.PostgreSQL" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
  </ItemGroup>

</Project>