<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Squirrel.Core\Squirrel.Core.csproj" />
    <ProjectReference Include="..\Squirrel.Validation\Squirrel.Validation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
    <PackageReference Include="WolverineFx.PostgreSQL" />
    <PackageReference Include="WolverineFx.RabbitMQ" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
  </ItemGroup>
  
  <ItemGroup Label="Aspire Packages">
    <PackageReference Include="Aspire.RabbitMQ.Client.v7" />
  </ItemGroup>
  
  <ItemGroup Label="Health Check">
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="AspNetCore.HealthChecks.Rabbitmq" />
  </ItemGroup>
  
  
</Project>
